### ISSUE TITLE
Builds at Travis failing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-snap#1]
Due to:

```
$ for adoc in ./tests/*.adoc; do metanorma compile $adoc; done
 is not a legal status
article is not a legal document type: reverting to 'standard'
Traceback (most recent call last):
	18: from /snap/metanorma/x1/bin/metanorma:23:in `<main>'
	17: from /snap/metanorma/x1/bin/metanorma:23:in `load'
	16: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.2/exe/metanorma:20:in `<top (required)>'
	15: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.2/lib/metanorma/cli.rb:56:in `start'
	14: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	13: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	12: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	11: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	10: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.2/lib/metanorma/cli/command.rb:34:in `compile'
	 9: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.2/lib/metanorma/cli/compiler.rb:15:in `compile'
	 8: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.2/lib/metanorma/cli/compiler.rb:11:in `compile'
	 7: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.2/lib/metanorma/cli/compiler.rb:23:in `compile_file'
	 6: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:20:in `compile'
	 5: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:183:in `process_extensions'
	 4: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:183:in `each'
	 3: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:192:in `block in process_extensions'
	 2: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-csd-1.2.1/lib/metanorma/csd/processor.rb:36:in `output'
	 1: from /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/isodoc-0.10.1/lib/isodoc/pdf_convert.rb:33:in `convert'
/snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.14/lib/metanorma/output/pdf.rb:18:in `convert': internal/modules/cjs/loader.js:670 (RuntimeError)
    throw err;
```

**Comment by CAMOBAP795** [comment]
Stacktrace above related to `puppeteer` module is not found, which fixed already by new own plugin `npm.py`

For now, we have another problem:

> /snap/metanorma/x1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.14/lib/metanorma/output/pdf.rb:18:in `convert': Protocol error (Target.setDiscoverTargets): Target closed. (RuntimeError)

I think https://github.com/metanorma/metanorma/commit/b6bdca3b0213faec988ca6fd5e6d3b2e58d5457c should fix this problem. but I should try first

Interesting that unit tests passed if run against the same file inside docker, so this issue reproduces only in snap package

**Comment by CAMOBAP795** [comment]
> metanorma/metanorma@b6bdca3

Doesn't help

**Comment by CAMOBAP795** [comment]
Highly likely it's related to execution permission for embedded chrome binary file

**Comment by ronaldtse** [comment]
@CAMOBAP795 https://forum.snapcraft.io/t/snapcraft-travis-ci-com-org-address-error/6552

the `snap enable-ci` command does not work with Travis COM and is no longer recommended.

The alternative is a manual setup, where we store the login token inside Travis.

```sh
apt-get update
apt-get install snapd snapcraft ruby ruby-dev libffi-dev make gcc g++ git -y
gem install travis
git clone https://github.com/metanorma/metanorma-snap
travis login --com --github-token=${GITHUB_TOKEN}
travis settings --com
snapcraft export-login --snaps metanorma --channels edge --acls package_upload -

# Copy out the token that it prints, set it as $SNAP_TOKEN
echo "$SNAP_TOKEN" | snapcraft login --with -
```

I've updated the Travis job for this repo to have the `SNAP_TOKEN` stored in the `snap_token` file, committed as `snap_token.enc` using Travis encryption.

**Comment by CAMOBAP795** [comment]
https://forum.snapcraft.io/t/mount-snap-with-rw-for-troubleshooting-propose/12264

**Comment by CAMOBAP795** [comment]
Still not fixed, after installation puppeteer embedded chrome use some resources/configs which have invalid paths because placed inside `/snap/metanorna` directory, at this point, I have found only
 - https://askubuntu.com/questions/492033/fontconfig-error-cannot-load-default-config-file

But it still doesn't work

Possible solution:
 - continue troubleshooting
 - skip pdf support for the first release 

*still looking for first item

**Comment by ronaldtse** [comment]
@CAMOBAP795 https://snapcraft.io/puppetry also installs Puppeteer but they can use it. Can you check? Thanks!

**Comment by ronaldtse** [comment]
Another potential example: https://github.com/stereobooster/react-snap/issues/311

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you act on this task? Thanks.

**Comment by CAMOBAP795** [comment]
not looked into it since last year, because problem is related to puppeteer which we will remove soon I propose to come back to it after https://github.com/metanorma/metanorma/issues/95

**Comment by CAMOBAP** [comment]
Done
