### ISSUE TITLE
Run tests on samples repositories instead of outdated local samples

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-snap#23]
### Problem

For now we do testing by compiling documents from [`test`](https://github.com/metanorma/metanorma-snap/tree/master/tests), and those docs looks outdated

### Proposed solution

As for `packed-mn` and `chocolatey` it's make sens to test snap on mn-samples-* repositories

**Comment by ronaldtse** [comment]
Agree @CAMOBAP !

**Comment by CAMOBAP** [comment]
Fixed
