### ISSUE TITLE
invalid-field: Track does not exist: 1.5.15.1

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-snap#24]
### Problem 

Version track doesn't work for some reason and according to https://snapcraft.io/metanorma looks like it never worked

It really helped to have an option to run the previous version of metanorma in case of some issues in a new ones

**Comment by CAMOBAP** [comment]
It looks like the track cannot contains four-digit, so only x.y.z is accepted

**Comment by ronaldtse** [comment]
@CAMOBAP can you make a proposal here? Maybe a dash like "1.5.15-1"?

**Comment by CAMOBAP** [comment]
Because this is not for the actual version but for `track`'s name (which is similar to the channel, on the screenshot below)

<img width="789" alt="Screen Shot 2022-05-19 at 6 53 20 PM" src="https://user-images.githubusercontent.com/2169738/169355489-3d8a5b4b-1311-4260-978f-6d3bd01e8644.png">

I think it's ok to drop anything except x.y.z

**Comment by ronaldtse** [comment]
Ok!

**Comment by CAMOBAP** [comment]
Fixed
