### ISSUE TITLE
Renew METANORMA_SNAPCRAFT_TOKEN

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-snap#35]
Looks like token has valid time 1 year 

And per README https://github.com/metanorma/metanorma-snap#generating-the-snapcraft-token it's expired today:

> ...
> expires:     2023-10-26T01:01:02.020303

@ronaldtse could you please help renew it (I have no access to secrets)

**Comment by CAMOBAP** [comment]
@ronaldtse friendly reminder

**Comment by CAMOBAP** [comment]
@ronaldtse 1.8.8 release blocked by this

**Comment by CAMOBAP** [comment]
@ronaldtse 1.8.10 release blocked by this

**Comment by CAMOBAP** [comment]
@ronaldtse [1.8.11 release blocked](https://github.com/metanorma/metanorma-snap/actions/runs/7341854625/job/19990880366) by this

**Comment by ronaldtse** [comment]
@CAMOBAP just updated!

**Comment by ronaldtse** [comment]
https://github.com/metanorma/metanorma-snap/actions/runs/7341854625

Passed.

<img width="1298" alt="Screenshot 2023-12-28 at 11 12 07 AM" src="https://github.com/metanorma/metanorma-snap/assets/11865/368ba111-197b-4f61-9187-b3b8e7cfa237">
