### ISSUE TITLE
Promote snap builds to Release/Candidate

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-snap#7]
Metanorma is not beta software and shouldn't be shown as such.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/11865/81905720-b0916200-95f7-11ea-854d-9d47f9e96efb.png">

**Comment by CAMOBAP** [comment]
Good point I will move it to stable after fixing https://github.com/metanorma/metanorma-snap/issues/5

**Comment by CAMOBAP** [comment]
Changed to candidate
